import {
  Html,
  Head,
  Body,
  Container,
  Section,
  Text,
  Heading,
  Hr,
  Row,
  Column,
} from '@react-email/components'
import { ChatInsights } from '@/types/insights'

interface InsightsEmailProps {
  insights: ChatInsights
}

export default function InsightsEmail({ insights }: InsightsEmailProps) {
  return (
    <Html>
      <Head />
      <Body style={main}>
        <Container style={container}>
          <Heading style={h1}>SynthChat Insights Report</Heading>
          <Text style={paragraph}>
            Analysis of synthetic chat data for in-house legal teams
          </Text>

          <Hr style={hr} />

          <Section style={section}>
            <Heading style={h2}>Executive Summary</Heading>
            <Row>
              <Column>
                <Text style={statNumber}>{insights.totalChats}</Text>
                <Text style={statLabel}>Total Conversations</Text>
              </Column>
              <Column>
                <Text style={statNumber}>{insights.timeSavings.totalHours}</Text>
                <Text style={statLabel}>Hours Saved</Text>
              </Column>
              <Column>
                <Text style={statNumber}>{insights.topics.length}</Text>
                <Text style={statLabel}>Topics Covered</Text>
              </Column>
            </Row>
          </Section>

          <Hr style={hr} />

          <Section style={section}>
            <Heading style={h2}>Time Savings by Lawyer Type</Heading>
            <Section style={timeSavingsBox}>
              <Row>
                <Column style={lawyerColumn}>
                  <Text style={lawyerType}>Privacy Lawyers</Text>
                  <Text style={timeStat}>
                    {insights.timeSavings.privacyLawyer.totalHours} hours
                  </Text>
                  <Text style={chatCount}>
                    ({insights.timeSavings.privacyLawyer.chatCount} chats)
                  </Text>
                  <Text style={averageTime}>
                    Avg: {Math.round(insights.timeSavings.privacyLawyer.totalMinutes / insights.timeSavings.privacyLawyer.chatCount)} min/chat
                  </Text>
                </Column>
                <Column style={lawyerColumn}>
                  <Text style={lawyerType}>Commercial Lawyers</Text>
                  <Text style={timeStat}>
                    {insights.timeSavings.commercialLawyer.totalHours} hours
                  </Text>
                  <Text style={chatCount}>
                    ({insights.timeSavings.commercialLawyer.chatCount} chats)
                  </Text>
                  <Text style={averageTime}>
                    Avg: {Math.round(insights.timeSavings.commercialLawyer.totalMinutes / insights.timeSavings.commercialLawyer.chatCount)} min/chat
                  </Text>
                </Column>
              </Row>
            </Section>
          </Section>

          <Hr style={hr} />

          <Section style={section}>
            <Heading style={h2}>Top Topics Discussed</Heading>
            {insights.topics.slice(0, 5).map((topic, index) => (
              <Section key={index} style={topicBox}>
                <Row>
                  <Column>
                    <Text style={topicName}>{topic.topic}</Text>
                    <Text style={topicCount}>
                      {topic.count} conversation{topic.count !== 1 ? 's' : ''} • {topic.percentage}%
                    </Text>
                  </Column>
                  <Column style={percentageColumn}>
                    <Text style={percentage}>{topic.percentage}%</Text>
                  </Column>
                </Row>
              </Section>
            ))}
          </Section>

          <Hr style={hr} />

          <Section style={section}>
            <Heading style={h2}>Most Frequently Asked Questions</Heading>
            {insights.topFAQs.slice(0, 5).map((faq, index) => (
              <Section key={index} style={faqBox}>
                <Text style={faqQuestion}>Q: {faq.question}</Text>
                <Text style={faqMeta}>
                  Asked {faq.frequency} time{faq.frequency !== 1 ? 's' : ''} • {faq.category}
                </Text>
              </Section>
            ))}
          </Section>

          <Hr style={hr} />

          <Section style={section}>
            <Heading style={h2}>Key Insights</Heading>
            {insights.keyInsights.map((insight, index) => (
              <Text key={index} style={insightItem}>
                • {insight}
              </Text>
            ))}
          </Section>

          <Hr style={hr} />

          <Text style={footer}>
            Generated by SynthChat • AI-driven synthetic chat analysis for legal teams
          </Text>
        </Container>
      </Body>
    </Html>
  )
}

const main = {
  backgroundColor: '#f6f9fc',
  fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Ubuntu,sans-serif',
}

const container = {
  backgroundColor: '#ffffff',
  margin: '0 auto',
  padding: '40px',
  marginTop: '20px',
  marginBottom: '20px',
  maxWidth: '600px',
  borderRadius: '8px',
}

const h1 = {
  color: '#1a1a1a',
  fontSize: '28px',
  fontWeight: 'bold',
  margin: '0 0 10px',
}

const h2 = {
  color: '#1a1a1a',
  fontSize: '20px',
  fontWeight: '600',
  margin: '30px 0 15px',
}

const paragraph = {
  color: '#666666',
  fontSize: '16px',
  lineHeight: '24px',
  margin: '0 0 20px',
}

const hr = {
  borderColor: '#e0e0e0',
  margin: '30px 0',
}

const section = {
  margin: '20px 0',
}

const statNumber = {
  fontSize: '36px',
  fontWeight: 'bold',
  color: '#2563eb',
  margin: '0',
  textAlign: 'center' as const,
}

const statLabel = {
  fontSize: '14px',
  color: '#666666',
  textAlign: 'center' as const,
  margin: '5px 0 0',
}

const timeSavingsBox = {
  backgroundColor: '#f8f9fa',
  padding: '20px',
  borderRadius: '6px',
  margin: '15px 0',
}

const lawyerColumn = {
  padding: '10px',
  textAlign: 'center' as const,
}

const lawyerType = {
  fontSize: '16px',
  fontWeight: '600',
  color: '#1a1a1a',
  margin: '0 0 10px',
}

const timeStat = {
  fontSize: '28px',
  fontWeight: 'bold',
  color: '#16a34a',
  margin: '5px 0',
}

const chatCount = {
  fontSize: '14px',
  color: '#666666',
  margin: '5px 0',
}

const averageTime = {
  fontSize: '12px',
  color: '#888888',
  margin: '5px 0 0',
}

const topicBox = {
  backgroundColor: '#f8f9fa',
  padding: '15px',
  borderRadius: '6px',
  margin: '10px 0',
}

const topicName = {
  fontSize: '16px',
  fontWeight: '600',
  color: '#1a1a1a',
  margin: '0 0 8px',
}

const barColumn = {
  width: '70%',
  paddingRight: '10px',
}

const percentageColumn = {
  width: '30%',
  textAlign: 'right' as const,
}

const barFill = {
  height: '8px',
  backgroundColor: '#2563eb',
  borderRadius: '4px',
}

const percentage = {
  fontSize: '14px',
  fontWeight: '600',
  color: '#2563eb',
  margin: '0',
}

const topicCount = {
  fontSize: '12px',
  color: '#666666',
  margin: '8px 0 0',
}

const faqBox = {
  padding: '15px 0',
  borderBottom: '1px solid #e0e0e0',
}

const faqQuestion = {
  fontSize: '15px',
  fontWeight: '600',
  color: '#1a1a1a',
  margin: '0 0 5px',
}

const faqMeta = {
  fontSize: '12px',
  color: '#888888',
  margin: '0',
}

const insightItem = {
  fontSize: '15px',
  color: '#1a1a1a',
  lineHeight: '24px',
  margin: '8px 0',
}

const footer = {
  fontSize: '12px',
  color: '#888888',
  textAlign: 'center' as const,
  margin: '30px 0 0',
}

